# Non-secure properties file
#
hl7:
   input-dir: "/Users/jvansant/Demos/B2B_Demo/HL7-demos/hl7-demo-in"
   output-dir: "/Users/jvansant/Demos/B2B_Demo/HL7-demos/hl7-demo-out"
   output-filename: "output.json"
   processed-dir: "/Users/jvansant/Demos/B2B_Demo/HL7-demos/hl7-demo-processed"
   
sftp:
   host: "eksprod.tools.mulesoft.com"
   port: "30380"
   inbound_dir: "/upload/inbound/HL7"
   outbound_dir: "/upload/outbound/HL7"
   output_filename: "HL7_ADT_A01_with_ZPM.hl7"
   archive_dir: "/upload/archive/HL7"