A01: { ADT: ADT_A01, ACK: ACK }
A02: { ADT: ADT_A02, ACK: ACK }
A03: { ADT: ADT_A03, ACK: ACK }
A04: { ADT: ADT_A01, ACK: ACK }
A05: { ADT: ADT_A01, ACK: ACK }
A06: { ADT: ADT_A06, ACK: ACK }
A07: { ADT: ADT_A06, ACK: ACK }
A08: { ADT: ADT_A01, ACK: ACK }
A09: { ADT: ADT_A09, ACK: ACK }
A10: { ADT: ADT_A09, ACK: ACK }
A11: { ADT: ADT_A09, ACK: ACK }
A12: { ADT: ADT_A12, ACK: ACK }
A13: { ADT: ADT_A01, ACK: ACK }
A14: { ADT: ADT_A01, ACK: ACK }
A15: { ADT: ADT_A09, ACK: ACK }
A16: { ADT: ADT_A16, ACK: ACK }
A17: { ADT: ADT_A17, ACK: ACK }
A18: { ADT: ADT_A18, ACK: ACK }
A19: { QRY: QRY_A19, ADR: ADR_A19 }
A20: { ADT: ADT_A20, ACK: ACK }
A21: { ADT: ADT_A02, ACK: ACK }
A22: { ADT: ADT_A02, ACK: ACK }
A23: { ADT: ADT_A02, ACK: ACK }
A24: { ADT: ADT_A24, ACK: ACK }
A25: { ADT: ADT_A02, ACK: ACK }
A26: { ADT: ADT_A02, ACK: ACK }
A27: { ADT: ADT_A02, ACK: ACK }
A28: { ADT: ADT_A01, ACK: ACK }
A29: { ADT: ADT_A02, ACK: ACK }
A30: { ADT: ADT_A30, ACK: ACK }
A31: { ADT: ADT_A01, ACK: ACK }
A32: { ADT: ADT_A02, ACK: ACK }
A33: { ADT: ADT_A02, ACK: ACK }
A34: { ADT: ADT_A30, ACK: ACK }
A35: { ADT: ADT_A30, ACK: ACK }
A36: { ADT: ADT_A30, ACK: ACK }
A37: { ADT: ADT_A24, ACK: ACK }
M01: { MFQ: MFQ_M01, MFR: MFR_M01, MFD: MFD_M01, ACK: ACK, MFN: MFN_M01, MFK: MFK_M01 }
M02: { MFQ: MFQ_M02, MFR: MFR_M02, MFD: MFD_M02, ACK: ACK, MFN: MFN_M02, MFK: MFK_M02 }
M03: { MFQ: MFQ_M03, MFR: MFR_M03, MFD: MFD_M03, ACK: ACK, MFN: MFN_M03, MFK: MFK_M03 }
N01: { NMD: NMD_N01, ACK: ACK }
N02: { NMQ: NMQ_N02, NMR: NMR_N02 }
O01: { ORM: ORM_O01, ACK: ACK }
O02: { ORR: ORR_O02, ACK: ACK }
P01: { BAR: BAR_P01, ACK: ACK }
P02: { BAR: BAR_P02, ACK: ACK }
P03: { DFT: DFT_P03, ACK: ACK }
P04: { QRY: QRY_P04, DSR: DSR_P04 }
Q01: { QRY: QRY_Q01, DSR: DSR_Q01 }
Q02: { QRY: QRY_Q02, ACK: ACK }
Q03: { DSR: DSR_Q03, ACK: ACK }
Q05: { UDM: UDM_Q05, ACK: ACK }
R01: { ORU: ORU_R01, ACK: ACK }
R02: { QRY: QRY_R02, ACK: ACK }
R03: { DSR: DSR_R03, ACK: ACK }
R04: { ORF: ORF_R04, ACK: ACK }
