# Non-secure properties file
#

sftp:
   host: "eksprod.tools.mulesoft.com"
   port: "30380"
   inbound_dir: "/upload/inbound/HL7"
   outbound_dir: "/upload/outbound/HL7"
   output_filename: "HL7_ADT_A01.json"
   archive_dir: "/upload/archive/HL7"