http:
  host: "0.0.0.0"
  port: "8081"
  
mllp_v2_2:
  host: "0.0.0.0"
  port: "8022"
  
mllp_v2_3:
  host: "0.0.0.0"
  port: "8023"

    
salesforce:
#  username: "admin@mulesoft.hcido.spr20.work.demo"
  username: "ydhimate@ydhimate-20200709.demo"
  url: "https://login.salesforce.com/services/Soap/u/47.0" 
#  consumerKey: "3MVG95jctIhbyCpopzITZ7lt37jLHMacfUV4DnnuVU_qRFKQRTcss2uNqLoX_atkhDalanLiTd383W51SZ.Uc"
#  consumerKey: "3MVG95jctIhbyCppoTXvwVGeOEHTdKny0nQLOzMKmswn9ol0uPnOqS_AUqmriOki29o6Y9asshM5poEoHy0qQ"
  consumerKey: "3MVG9Kip4IKAZQEUHy2mFm5aT41yRpE69nAGtiKL_xrRChAfaY.qKnAb4Yqq16A_IYlRKBcAvayRduXSYPKvT"
   
anypoint:
  mq:
    client_id: "2534b6b2f1a8444d89812ab983b40aef"

until:
  successful:
    maxretries: "3"
    timebetween: "3000"
 
