salesforce:
   password: "![74wwCGyD/vyPRkrcanKR7g==]"
#  consumerSecret: "![NsoF4bLOyKbtfAg9Z8Kls77X5dsru8CBQ4Pdg97XCPt50vqZW3Km2Ekl+6p5Usj5iCOWCLHNW0HV2Nhwodz3vZ8NkqicgzgF]"
#   consumerSecret: "![m+SVA4HtEK+/fbL9o1VxWF4GqCpysZJqfIzh9pAUqoQWk0NyaqZikiCCk2qOQHxIZaKQXu7/nIj9f9kPeVp8zygXbgwjIbPv]"
   consumerSecret: "![nmIpbYbTcr9pwKtaSxHiWfQxHJr8pZmOl/V5jnqlVwDw1vk0Cr/CYIcR8aAPG5FjKuepSthlfK9jjgQkS4nOD/JuJFb4ZcGq]"
     
anypoint:
  mq:
    client_secret: "![feEahX94rOwjAPDCNs+PZG0RT5lleZPg4gAA09Omf3dDUL4UOi0EyQ==]"
  