salesforce:
  password: "![74wwCGyD/vyPRkrcanKR7g==]"
  consumerSecret: "![NsoF4bLOyKbtfAg9Z8Kls77X5dsru8CBQ4Pdg97XCPt50vqZW3Km2Ekl+6p5Usj5iCOWCLHNW0HV2Nhwodz3vZ8NkqicgzgF]"
  
anypoint:
  mq:
    client_secret: "![feEahX94rOwjAPDCNs+PZG0RT5lleZPg4gAA09Omf3dDUL4UOi0EyQ==]"
  
