A01: { ADT: ADT_A01, ACK: ACK }
A02: { ADT: ADT_A02, ACK: ACK }
A03: { ADT: ADT_A03, ACK: ACK }
A04: { ADT: ADT_A04, ACK: ACK }
A05: { ADT: ADT_A05, ACK: ACK }
A06: { ADT: ADT_A06, ACK: ACK }
A07: { ADT: ADT_A07, ACK: ACK }
A08: { ADT: ADT_A08, ACK: ACK }
A09: { ADT: ADT_A09, ACK: ACK }
A10: { ADT: ADT_A10, ACK: ACK }
A11: { ADT: ADT_A11, ACK: ACK }
A12: { ADT: ADT_A12, ACK: ACK }
A13: { ADT: ADT_A13, ACK: ACK }
A14: { ADT: ADT_A14, ACK: ACK }
A15: { ADT: ADT_A15, ACK: ACK }
A16: { ADT: ADT_A16, ACK: ACK }
A17: { ADT: ADT_A17, ACK: ACK }
A20: { ADT: ADT_A20, ACK: ACK }
A21: { ADT: ADT_A21, ACK: ACK }
A22: { ADT: ADT_A22, ACK: ACK }
A23: { ADT: ADT_A23, ACK: ACK }
A24: { ADT: ADT_A24, ACK: ACK }
A25: { ADT: ADT_A25, ACK: ACK }
A26: { ADT: ADT_A26, ACK: ACK }
A27: { ADT: ADT_A27, ACK: ACK }
A28: { ADT: ADT_A28, ACK: ACK }
A29: { ADT: ADT_A29, ACK: ACK }
A31: { ADT: ADT_A31, ACK: ACK }
A32: { ADT: ADT_A32, ACK: ACK }
A33: { ADT: ADT_A33, ACK: ACK }
A37: { ADT: ADT_A37, ACK: ACK }
A38: { ADT: ADT_A38, ACK: ACK }
A40: { ADT: ADT_A40, ACK: ACK }
A41: { ADT: ADT_A41, ACK: ACK }
A42: { ADT: ADT_A42, ACK: ACK }
A43: { ADT: ADT_A43, ACK: ACK }
A44: { ADT: ADT_A44, ACK: ACK }
A45: { ADT: ADT_A45, ACK: ACK }
A47: { ADT: ADT_A47, ACK: ACK }
A49: { ADT: ADT_A49, ACK: ACK }
A50: { ADT: ADT_A50, ACK: ACK }
A51: { ADT: ADT_A51, ACK: ACK }
A52: { ADT: ADT_A52, ACK: ACK }
A53: { ADT: ADT_A53, ACK: ACK }
A54: { ADT: ADT_A54, ACK: ACK }
A55: { ADT: ADT_A55, ACK: ACK }
A60: { ADT: ADT_A60, ACK: ACK }
A61: { ADT: ADT_A61, ACK: ACK }
A62: { ADT: ADT_A62, ACK: ACK }